name: 'Close stale issues'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/stale@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: >
            This issue has been automatically marked as stale because it has not had
            activity within the last 30 days. It will be closed if no further activity occurs. Thank you
            for your contributions.
          days-before-stale: 30
          stale-issue-label: 'stale'
          exempt-issue-labels: 'pinned,security'
